[dependencies]

[package]
  cjc-version = "0.51.4"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "imgui"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

# [ffi.c]
#   cimgui = { path = "src/libs" }
#   cimgui_impl = { path = "src/libs" }
