[dependencies]

[package]
  cjc-version = "0.53.4"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "imgui4cj"
  output-type = "dynamic"
  src-dir = ""
  target-dir = ""
  version = "0.1.0"
  package-configuration = {}

[ffi.c]
  imgui4cj_c_lib = { path = "src/libs" }
