[dependencies]
  # imgui4cj = { path = "../../", version = "0.1.0"}

[package]
  cjc-version = "0.53.4"
  compile-option = ""
  description = "nothing here"
  link-option = ""
  name = "helloworld"
  output-type = "executable"
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}

# To avoid unnecessary compilation, binary dependencies are manually specified.
# Users can use imgui4cj by directly adding `imgui4cj = { path = "/path/to/imgui4cj", version = "0.1.0" }` to their [dependencies].

[ffi.c]
  imgui4cj_c_lib = { path = "../../src/libs" }

[target.x86_64-unknown-linux-gnu.bin-dependencies.package-option]
  "imgui4cj.utils" = "../../target/release/imgui4cj/imgui4cj.utils.cjo"
  "imgui4cj.capi_impl" = "../../target/release/imgui4cj/imgui4cj.capi_impl.cjo"
  "imgui4cj.capi" = "../../target/release/imgui4cj/imgui4cj.capi.cjo"
  "imgui4cj.wcapi" = "../../target/release/imgui4cj/imgui4cj.wcapi.cjo"
  "imgui4cj.backends" = "../../target/release/imgui4cj/imgui4cj.backends.cjo"
  "imgui4cj" = "../../target/release/imgui4cj/imgui4cj.cjo"

[target.x86_64-w64-mingw32.bin-dependencies.package-option]
  "imgui4cj.utils" = "../../target/release/imgui4cj/imgui4cj.utils.cjo"
  "imgui4cj.capi_impl" = "../../target/release/imgui4cj/imgui4cj.capi_impl.cjo"
  "imgui4cj.capi" = "../../target/release/imgui4cj/imgui4cj.capi.cjo"
  "imgui4cj.wcapi" = "../../target/release/imgui4cj/imgui4cj.wcapi.cjo"
  "imgui4cj.backends" = "../../target/release/imgui4cj/imgui4cj.backends.cjo"
  "imgui4cj" = "../../target/release/imgui4cj/imgui4cj.cjo"
